CREATE TABLE IF NOT EXISTS models
(
	id	INTEGER NOT NULL PRIMARY KEY,
	key 	VARCHAR(255),
	value	VARCHAR(255),
	created_date	TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	updated_date	TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (user_id) REFERENCES users(id)
);
